version: "3.7"

services:
  ghost:
    networks:
      - shared_backend
    image: ghost:3.38.3
    ports:
      - "8888:2368"
    restart: always
    env_file: .env
    volumes:
      - ./content:/var/lib/ghost/content/
  mysql:
    container_name: shared_mysql
    image: mysql:5.7.29
    restart: always
    env_file: .env
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - shared_backend
    ports:
      - 3306:3306
  mail:
    image: mailhog/mailhog:v1.0.1
    container_name: mail
    ports:
      - 8025:8025
    networks:
      - shared_backend
      

networks:
    shared_backend:
        name: shared_backend
        # use a custom driver, with no options
        driver: bridge