version: '3.7'

services:
   ghost:
     user: "${UID}:${GID}"
     external_links:
       - shared_mysql
     networks:
       - shared_backend
     image: geekbeacon/gb-ghost:4.16.0
     ports:
       - "8888:2368"
     restart: always
     env_file: .env
     volumes:
       - ./content:/var/lib/ghost/content/

networks:
    shared_backend:
        name: shared_backend
        external: true
